let PRODUCTS=[];let WISH=new Set();
function offerHtml(p){ const hasOffer = Number(p.id)%5!==0; const mrp = hasOffer ? Math.ceil(Number(p.price)*1.25/50)*50 : Number(p.price); return hasOffer ? `<del>${fmtINR(mrp)}</del> <span class="offer-price">${fmtINR(p.price)}</span><span class="discount-badge">${Math.round((1-p.price/mrp)*100)}% OFF</span>` : `<span class="new-arrival">New Arrival</span> <span class="offer-price">${fmtINR(p.price)}</span>`; }
function stars(r){return '★'.repeat(Math.round(r))+'☆'.repeat(5-Math.round(r))}
async function loadProducts(cat){const d=await api(`/api/products${cat&&cat!=='All'?`?cat=${encodeURIComponent(cat)}`:''}`);PRODUCTS=d.products;WISH=await wishlistIds();renderProductGrid();}
function cardHtml(p){const wished=WISH.has(p.id);const cart=cartRead();const line=cart.find(c=>c.id===p.id);const qty=line?.qty||0;return `<article class="card" id="card-${p.id}"><div class="card-media"><a href="product.html?id=${p.id}" class="product-link"><div class="imgwrap"><img src="${productImg(p)}" alt="${escapeHtml(p.name)}" loading="lazy"></div></a><button class="wish-btn ${wished?'active':''}" aria-label="Wishlist" onclick="toggleCardWish(${p.id},this)">${wished?'♥':'♡'}</button></div><div class="info"><div class="cat-label">${escapeHtml(p.category)}</div><h3><a href="product.html?id=${p.id}">${escapeHtml(p.name)}</a></h3><div class="rating">${Number(p.reviewCount||0)>0?stars(Number(p.rating||0))+' <span>'+Number(p.reviewCount)+' reviews</span>':'<span>Be the first to review</span>'}</div><div class="price">${offerHtml(p)}</div><div class="size-note">Sizes: ${escapeHtml(p.sizes.join(', '))}</div><div class="stock-label">${p.stock>0?'In stock':'Currently unavailable'}</div><div class="card-actions"><a class="btn ghost" href="product.html?id=${p.id}">View details</a><button class="btn" onclick="addToCart(${p.id},true)">${qty?'Add another':'Add to bag'}</button></div></div></article>`}
function renderProductGrid(){const grid=document.getElementById('productGrid');if(!grid)return;const count=document.getElementById('prodCount');if(count)count.textContent=`${PRODUCTS.length} curated products`;grid.innerHTML=PRODUCTS.map(cardHtml).join('')}
async function toggleCardWish(id,btn){try{const has=WISH.has(id);if(has){await api(`/api/wishlist/${id}`,{method:'DELETE'});WISH.delete(id);btn.classList.remove('active');btn.textContent='♡'}else{await api(`/api/wishlist/${id}`,{method:'POST'});WISH.add(id);btn.classList.add('active');btn.textContent='♥'}}catch(e){if(e.message.includes('log in'))location.href='login.html';else alert(e.message)}}
function addToCart(id,showNotice,size){const p=PRODUCTS.find(x=>x.id===Number(id))||window.CURRENT_PRODUCT;if(!p||!p.stock)return;const selected=size||p.sizes[0];let cart=cartRead();const line=cart.find(c=>c.id===p.id&&c.size===selected);if(line){if(line.qty<p.stock)line.qty++}else cart.push({id:p.id,qty:1,size:selected});cartWrite(cart);if(showNotice&&typeof showAddedToast==='function')showAddedToast(p);renderProductGrid()}
function cardChangeQty(id,delta){let cart=cartRead();const line=cart.find(c=>c.id===id);if(!line)return;line.qty+=delta;if(line.qty<=0)cart=cart.filter(c=>c!==line);cartWrite(cart);renderProductGrid()}
function renderCategoryFilter(initial){const wrap=document.getElementById('catFilter');if(!wrap)return;const cats=['All','Men','Women','Kids','Fashion'];wrap.innerHTML=cats.map(c=>`<button class="chip ${c===initial?'active':''}" data-cat="${c}" onclick="applyCategory('${c}',this)">${c}</button>`).join('');if(!initial){wrap.querySelector('.chip').classList.add('active')}}
async function applyCategory(cat,btn){document.querySelectorAll('#catFilter .chip').forEach(b=>b.classList.remove('active'));btn?.classList.add('active');await loadProducts(cat)}
document.addEventListener('DOMContentLoaded',async()=>{const initial=new URLSearchParams(location.search).get('cat')||'All';renderCategoryFilter(initial);try{await loadProducts(initial)}catch(e){document.getElementById('productGrid').innerHTML=`<div class="empty">${escapeHtml(e.message)}</div>`}});
