let checkoutProducts=[];
async function getCheckoutData(){const cart=cartRead();const products=(await api('/api/products')).products;let subtotal=0;const lines=[];for(const c of cart){const p=products.find(x=>x.id===c.id);if(p){subtotal+=p.price*c.qty;lines.push({...c,product:p})}}const shipping=subtotal>=FREE_SHIPPING_MIN?0:SHIPPING_FEE;return {cart:lines,subtotal,shipping,total:subtotal+shipping}}
function showCheckoutMsg(text,error=true){const el=document.getElementById('checkoutMsg');el.textContent=text;el.className=`msg ${error?'err ':''}show`}
async function renderCheckoutSummary(){const el=document.getElementById('checkoutSummary');if(!el)return;const d=await getCheckoutData();el.innerHTML=`${d.cart.map(c=>`<div class="row"><span>${escapeHtml(c.product.name)} × ${c.qty}</span><span>${fmtINR(c.product.price*c.qty)}</span></div>`).join('')}<div class="row"><span>Delivery</span><span>${d.shipping?fmtINR(d.shipping):'Free'}</span></div><div class="row total"><span>Total</span><span>${fmtINR(d.total)}</span></div>`}
async function fillUser(){try{const u=(await api('/api/auth/me')).user;DB.write('sh_user',u);document.getElementById('co_name').value=u.name||'';document.getElementById('co_email').value=u.email||'';document.getElementById('co_phone').value=u.mobile||'';const a=u.address||{};document.getElementById('co_addr').value=a.address||'';document.getElementById('co_area').value=a.area||'';document.getElementById('co_city').value=a.city||'';document.getElementById('co_state').value=a.state||'';document.getElementById('co_pin').value=a.pin||'';document.getElementById('co_latitude').value=a.latitude??'';document.getElementById('co_longitude').value=a.longitude??''}catch{location.href='login.html?redirect=checkout.html'}}
function shippingForm(){return {name:document.getElementById('co_name').value.trim(),email:document.getElementById('co_email').value.trim(),phone:document.getElementById('co_phone').value.trim(),address:document.getElementById('co_addr').value.trim(),area:document.getElementById('co_area').value.trim(),city:document.getElementById('co_city').value.trim(),state:document.getElementById('co_state').value.trim(),pin:document.getElementById('co_pin').value.trim(),latitude:document.getElementById('co_latitude').value,longitude:document.getElementById('co_longitude').value}}
async function startCheckout(e){e.preventDefault();if(!requireLogin())return;const d=await getCheckoutData();if(!d.cart.length)return showCheckoutMsg('Your bag is empty.');if(!document.getElementById('co_policy').checked)return showCheckoutMsg('Please accept the non-refundable order policy.');const mode=document.querySelector('input[name="paymentMode"]:checked')?.value;if(!mode)return showCheckoutMsg('Select a payment method.');const shipping=shippingForm();if(!/^[6-9]\d{9}$/.test(shipping.phone)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(shipping.email)||!/^[1-9]\d{5}$/.test(shipping.pin))return showCheckoutMsg('Please enter valid delivery details.');const items=d.cart.map(c=>({id:c.product.id,qty:c.qty,size:c.size}));const btn=document.getElementById('payBtn');btn.disabled=true;btn.textContent=mode==='cod'?'Placing order…':'Opening secure payment…';try{if(mode==='cod'){const r=await api('/api/orders/cod',{method:'POST',body:JSON.stringify({items,shipping})});completeOrder(r.order,'Cash on Delivery');return;}const order=await api('/api/payment/create-order',{method:'POST',body:JSON.stringify({items})});const options={key:order.keyId,amount:order.amount,currency:order.currency||'INR',name:'Style Heaven',description:'Style Heaven order',order_id:order.id,prefill:{name:shipping.name,email:shipping.email,contact:'+91'+shipping.phone},theme:{color:'#5B1636'},handler:async response=>{try{const verified=await api('/api/payment/verify',{method:'POST',body:JSON.stringify({...response,items,shipping})});completeOrder(verified.order,'Razorpay Online')}catch(err){showCheckoutMsg(err.message);btn.disabled=false;btn.textContent='Proceed to Pay'}},modal:{ondismiss:()=>{btn.disabled=false;btn.textContent='Proceed to Pay'}}};new Razorpay(options).open()}catch(err){showCheckoutMsg(err.message);btn.disabled=false;btn.textContent='Proceed to Pay'}}
function completeOrder(order,mode){DB.write('sh_cart',[]);document.getElementById('orderSummary').innerHTML=`Order <strong>${escapeHtml(order.orderId)}</strong> has been placed successfully.<br><span class="note">${fmtINR(order.total)} · ${escapeHtml(mode)}</span>`;document.getElementById('checkoutFormWrap').style.display='none';document.getElementById('orderSuccess').style.display='block';renderNav()}
document.addEventListener('DOMContentLoaded',async()=>{if(!requireLogin())return;await fillUser();await renderCheckoutSummary();document.getElementById('checkoutForm')?.addEventListener('submit',startCheckout)});
